### ISSUE TITLE
Why the code of  229 is KeyQ?

### ISSUE THREAD

**Issue by sxwxs** [marijnh/w3c-keycode#1]
Hi! I found that in [index.js line 54](https://github.com/marijnh/w3c-keycode/blob/master/index.js#L54) code 229  corresponds to "KeyQ". But this [page](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) shows that keycode 229 may occur in many cases.

**Comment by marijnh** [comment]
I can't find out why I added that. It appears to have been part of the initial code, which I based on CodeMirror's key name map... but that one doesn't have this entry. So I guess it is complete nonsense. Attached patch removes it.

**Comment by sxwxs** [comment]
Thank you for the quick reply. :)
